Substitute own rust project (broken)
I get a weird DNS error:

$ nix-shell .
these derivations will be built:
  /nix/store/mi1ik4vz65nbq2sw1mkwa4zz4n81isf2-hello-0.4.0-fetch.drv
building path(s) ‘/nix/store/8vxmk96nqpwyyy6piarsg4k6nhd8mli0-hello-0.4.0-fetch’
unpacking sources
unpacking source archive /nix/store/9af3xk0353fx5njcbickamvpdyss4xr8-rust
source root is rust
installing
Fetching /tmp/nix-build-hello-0.4.0-fetch.drv-0/rust to /nix/store/8vxmk96nqpwyyy6piarsg4k6nhd8mli0-hello-0.4.0-fetch
Setting up git templatedir
Using rust registry from /nix/store/4jswq986dfzdy3y0crajws9994lv2d0w-rustRegistry-2017-08-27
warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
    Updating registry `file:///nix/store/4jswq986dfzdy3y0crajws9994lv2d0w-rustRegistry-2017-08-27`
 Downloading bytecount v0.2.0 (registry file:///nix/store/4jswq986dfzdy3y0crajws9994lv2d0w-rustRegistry-2017-08-27)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates.io)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates.io)
error: unable to get packages from source

Caused by:
  [6] Couldn't resolve host name (Could not resolve host: crates.io)
builder for ‘/nix/store/mi1ik4vz65nbq2sw1mkwa4zz4n81isf2-hello-0.4.0-fetch.drv’ failed with exit code 101
error: build of ‘/nix/store/mi1ik4vz65nbq2sw1mkwa4zz4n81isf2-hello-0.4.0-fetch.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies

$ curl https://crates.io
{"errors":[{"detail":"Not Found"}]}